name: Run SSHX

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-sshx:
    runs-on: ubuntu-latest

    steps:
      - name: Run SSHX command
        run: curl -sSf https://sshx.io/get | sh -s run
